pipeline {
  agent {
    docker { image 'node:17-alpine' }
  }
  stages {
    stage('Dev') {
      steps {
        sh 'node --version'
      }
    }
       stage('Test') {
      steps {
        sh 'node --version'
      }
   
       }

    stage('prod') {
      steps {
        sh 'node --version'
      }
  }
}
}
